server:
  port: 2021
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: hbstudent
    url: jdbc:mysql://localhost:3306/healthcare
    username: hbstudent
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
